name: conda-monoface-py311
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ca-certificates
  - openssl
  - nvidia::cuda-toolkit=12.1
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pytorch3d
  - numpy
  - scipy
  - imageio
  - opencv
  - matplotlib
  - scikit-image
  - tqdm
  - pyyaml
  - click
  - requests
  - filelock
  - jinja2
  - typing-extensions
  - packaging
  - pillow
  - ffmpeg
  - yaml
  - pip:
      - tensorflow==2.11.0
      - keras==2.11.0
      - mtcnn
      - face-alignment
      - fvcore
      - iopath
      - yacs
      - opencv-python
      - matplotlib
      - tqdm
      - scipy
      - scikit-image
      - lightning
      - pytorch-lightning
      - transformers
      - tensorboard
      - rich
